In [1]:
import pandas as pd
import numpy as np

df  = pd.read_csv("Home_Price_prediction.csv")
df

Area         Price  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5  \
0   1000  3.164041e+05         NaN         NaN         NaN         NaN   
1   1500  3.842979e+05         NaN         NaN         NaN         NaN   
2   2300  4.929281e+05         NaN         NaN         NaN         NaN   
3   3540  6.613048e+05         NaN         NaN         NaN         NaN   
4   4120  7.400616e+05         NaN         NaN         NaN         NaN   
5   4560  7.998082e+05         NaN         NaN         NaN         NaN   
6   5490  9.260908e+05         NaN         NaN         NaN         NaN   
7   3460  6.504418e+05         NaN         NaN         NaN         NaN   
8   4750  8.256079e+05         NaN         NaN         NaN         NaN   
9   2300  4.929281e+05         NaN         NaN         NaN         NaN   
10  9000  1.402705e+06         NaN         NaN         NaN         NaN   
11  8600  1.348390e+06         NaN         NaN         NaN         NaN   
12  7100  1.144709e+06         NaN         NaN         NaN         NaN   

    Unnamed: 6  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          NaN  
10         NaN  
11         NaN  
12         NaN

In [2]:
df.shape

(13, 7)

In [3]:
df.columns

Index(['Area', 'Price', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6'],
      dtype='object')

In [4]:
df = df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4',
              'Unnamed: 5','Unnamed: 6'],axis = 1)

In [5]:
df

Area         Price
0   1000  3.164041e+05
1   1500  3.842979e+05
2   2300  4.929281e+05
3   3540  6.613048e+05
4   4120  7.400616e+05
5   4560  7.998082e+05
6   5490  9.260908e+05
7   3460  6.504418e+05
8   4750  8.256079e+05
9   2300  4.929281e+05
10  9000  1.402705e+06
11  8600  1.348390e+06
12  7100  1.144709e+06

In [6]:
df.columns

Index(['Area', 'Price'], dtype='object')

In [9]:
X = df['Area']
y = df['Price']

In [10]:
X_train = X[:11]
X_test = X[11:]

In [11]:
X_train

0     1000
1     1500
2     2300
3     3540
4     4120
5     4560
6     5490
7     3460
8     4750
9     2300
10    9000
Name: Area, dtype: int64

In [12]:
X_train = np.array(X_train).reshape(-1,1)
X_train 

array([[1000],
       [1500],
       [2300],
       [3540],
       [4120],
       [4560],
       [5490],
       [3460],
       [4750],
       [2300],
       [9000]], dtype=int64)

In [13]:
X_test = np.array(X_test).reshape(-1,1)

In [14]:
y_train = y[:11]
y_test = y[11:]

In [15]:
Y_train = np.array(y_train).reshape(-1, 1)
Y_train

array([[ 316404.10958904],
       [ 384297.94520548],
       [ 492928.08219178],
       [ 661304.79452055],
       [ 740061.64383562],
       [ 799808.21917808],
       [ 926090.75342466],
       [ 650441.78082192],
       [ 825607.87671233],
       [ 492928.08219178],
       [1402705.47945206]])

In [20]:
from sklearn.linear_model import LinearRegression
my_model = LinearRegression()

In [18]:
#train the model 
my_model.fit(X_train,y_train)

NameError: name 'my_model' is not defined

In [22]:
#predict
prediction = my_model.predict(X_test)

In [23]:
prediction.reshape(-1,1)

array([[1348390.41095891],
       [1144708.90410959]])

In [24]:
y_test

11    1.348390e+06
12    1.144709e+06
Name: Price, dtype: float64

In [34]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,prediction)

2.7023739149201198e-17

In [244]:
my_model.predict([[7100]])
my_model.score()

array([1144708.90410959])